package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import static main.Login.txtName;
import net.proteanit.sql.DbUtils;

public class Pharmacy extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pre = null;
    ResultSet res = null;
    static int ex;
    User user;
    static Drug drug;
    static Customer customer;
    static SupplierPurchase supplierPurchase;
    static Supplier supplier;
    static BuyDrug buydrug;
    static PurchaseHistory purchaseHistory;
    static Capital capital;
    static FinancialTransaction transaction;
    Date d;
    SimpleDateFormat dd;
    private Timer capitalTimer;

    public Pharmacy() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(Pharmacy.class.getResource("/img/Untitled.png")));
        initComponents();
        con = Connect.connect();
        showDate();
        buttonvis();
        user = new User();
        drug = new Drug();
        customer = new Customer();
        supplier = new Supplier();
        buydrug = new BuyDrug();
        purchaseHistory = new PurchaseHistory();
        supplierPurchase = new SupplierPurchase();
        capital = new Capital();
        transaction = new FinancialTransaction();
        lbl_LoginAs.setText(Login.NAME);
        lbl_Type.setText(Login.TYPE);

        capitalTimer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateCapitalLabelOnOtherForm();
            }
        });
        capitalTimer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUserDet = new javax.swing.JButton();
        btnDrugsDet = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnAddDrug = new javax.swing.JButton();
        btnSearchDrug = new javax.swing.JButton();
        btnExpiredDrugs = new javax.swing.JButton();
        btnAlmostF = new javax.swing.JButton();
        btnCustomerDet = new javax.swing.JButton();
        btnPurchaseDet = new javax.swing.JButton();
        btnPurchaseH = new javax.swing.JButton();
        btnCreateBill = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();
        btnSupplierDet = new javax.swing.JButton();
        btnAddSupplierPurchase = new javax.swing.JButton();
        btnFinancialTransaction = new javax.swing.JButton();
        btnAddCapital = new javax.swing.JButton();
        btnCapitalDet = new javax.swing.JButton();
        btnAddSupplier = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        today = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lbl_LoginAs = new javax.swing.JLabel();
        lbl_Type = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblCurrentCapitalOnOtherForm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy Management");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        btnUserDet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserDet.setText("User Details");
        btnUserDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDetActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserDet);
        btnUserDet.setBounds(1000, 100, 140, 34);

        btnDrugsDet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDrugsDet.setText("Drugs Details");
        btnDrugsDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugsDetActionPerformed(evt);
            }
        });
        jPanel1.add(btnDrugsDet);
        btnDrugsDet.setBounds(670, 100, 150, 34);

        btnAddUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddUser);
        btnAddUser.setBounds(1000, 150, 140, 22);

        btnAddDrug.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddDrug.setText("Add Drug");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddDrug);
        btnAddDrug.setBounds(670, 150, 150, 22);

        btnSearchDrug.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchDrug.setText("Search Drug");
        btnSearchDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDrugActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchDrug);
        btnSearchDrug.setBounds(670, 240, 150, 22);

        btnExpiredDrugs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExpiredDrugs.setText("Expired Drugs");
        btnExpiredDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredDrugsActionPerformed(evt);
            }
        });
        jPanel1.add(btnExpiredDrugs);
        btnExpiredDrugs.setBounds(670, 180, 150, 22);

        btnAlmostF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlmostF.setText("Almost Finished");
        btnAlmostF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmostFActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlmostF);
        btnAlmostF.setBounds(670, 210, 150, 22);

        btnCustomerDet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCustomerDet.setText("Customer Details");
        btnCustomerDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDetActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomerDet);
        btnCustomerDet.setBounds(330, 100, 150, 34);

        btnPurchaseDet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPurchaseDet.setText("Purchase Details");
        btnPurchaseDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseDetActionPerformed(evt);
            }
        });
        jPanel1.add(btnPurchaseDet);
        btnPurchaseDet.setBounds(500, 100, 150, 34);

        btnPurchaseH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPurchaseH.setText("Purchase History");
        btnPurchaseH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseHActionPerformed(evt);
            }
        });
        jPanel1.add(btnPurchaseH);
        btnPurchaseH.setBounds(500, 180, 150, 22);

        btnCreateBill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreateBill.setText("Create Bill");
        btnCreateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateBill);
        btnCreateBill.setBounds(500, 150, 150, 22);

        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddCustomer);
        btnAddCustomer.setBounds(330, 150, 150, 22);

        btnSupplierDet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSupplierDet.setText("Supplier Details");
        btnSupplierDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierDetActionPerformed(evt);
            }
        });
        jPanel1.add(btnSupplierDet);
        btnSupplierDet.setBounds(160, 100, 150, 34);

        btnAddSupplierPurchase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddSupplierPurchase.setText("Make a Deal");
        btnAddSupplierPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierPurchaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddSupplierPurchase);
        btnAddSupplierPurchase.setBounds(160, 180, 150, 22);

        btnFinancialTransaction.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFinancialTransaction.setText("Transactions");
        btnFinancialTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancialTransactionActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinancialTransaction);
        btnFinancialTransaction.setBounds(840, 180, 140, 22);

        btnAddCapital.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddCapital.setText("Add Capital");
        btnAddCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCapitalActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddCapital);
        btnAddCapital.setBounds(840, 150, 140, 22);

        btnCapitalDet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCapitalDet.setText("Capital Details");
        btnCapitalDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapitalDetActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapitalDet);
        btnCapitalDet.setBounds(840, 100, 140, 34);

        btnAddSupplier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddSupplier.setText("Add Supplier");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddSupplier);
        btnAddSupplier.setBounds(160, 150, 150, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image (2).v5.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 80, 1300, 550);

        jPanel3.setBackground(new java.awt.Color(176, 137, 104));

        today.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        today.setForeground(new java.awt.Color(88, 49, 1));
        today.setText("00-00-0000");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Today");

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pharmacy Management");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Time");

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(243, 213, 181));
        time.setText("00:00:00");

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-power-off-65 (1).png"))); // NOI18N
        btnExit.setToolTipText("Logout");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Welcome");

        lblType.setBackground(new java.awt.Color(51, 51, 51));
        lblType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblType.setText("Status:");

        lbl_LoginAs.setBackground(new java.awt.Color(255, 255, 255));
        lbl_LoginAs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_LoginAs.setForeground(new java.awt.Color(255, 255, 255));
        lbl_LoginAs.setText(" ");

        lbl_Type.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Type.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Type.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Type.setText(" ");

        btnSettings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-settings-50 (5).png"))); // NOI18N
        btnSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log out.png"))); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Capital:");

        lblCurrentCapitalOnOtherForm.setBackground(new java.awt.Color(51, 51, 51));
        lblCurrentCapitalOnOtherForm.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblCurrentCapitalOnOtherForm.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_LoginAs, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(103, 103, 103)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(today, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurrentCapitalOnOtherForm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_LoginAs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Type)
                            .addComponent(lblType))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time)
                            .addComponent(today, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCurrentCapitalOnOtherForm, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1300, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1315, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        settings();
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnSearchDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDrugActionPerformed
        new Search_Drug().setVisible(true);
    }//GEN-LAST:event_btnSearchDrugActionPerformed

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed
        drug.setVisible(true);
    }//GEN-LAST:event_btnAddDrugActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        user.setVisible(true);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDrugsDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugsDetActionPerformed
        enterdrugs();
    }//GEN-LAST:event_btnDrugsDetActionPerformed

    private void btnUserDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDetActionPerformed

        if ("Admin".equals(Login.TYPE)) {
            enteruser();
        } else {
            JOptionPane.showMessageDialog(this, "You do not have permission to enter this field", "Access Denied", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUserDetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExpiredDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredDrugsActionPerformed
        new Expired_Drug().setVisible(true);
    }//GEN-LAST:event_btnExpiredDrugsActionPerformed

    private void btnAlmostFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmostFActionPerformed
        new Almost_Finish().setVisible(true);
    }//GEN-LAST:event_btnAlmostFActionPerformed

    private void btnCustomerDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDetActionPerformed
        entercustomer();
    }//GEN-LAST:event_btnCustomerDetActionPerformed

    private void btnPurchaseDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseDetActionPerformed
        enterpurchase();
    }//GEN-LAST:event_btnPurchaseDetActionPerformed

    private void btnPurchaseHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseHActionPerformed
        purchaseHistory.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        purchaseHistory.setVisible(true);
    }//GEN-LAST:event_btnPurchaseHActionPerformed

    private void btnCreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBillActionPerformed
        buydrug.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        buydrug.setVisible(true);
    }//GEN-LAST:event_btnCreateBillActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed

        customer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        customer.setVisible(true);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnSupplierDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierDetActionPerformed
        entersupplier();
    }//GEN-LAST:event_btnSupplierDetActionPerformed

    private void btnAddSupplierPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierPurchaseActionPerformed
        supplierPurchase.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        supplierPurchase.setVisible(true);
    }//GEN-LAST:event_btnAddSupplierPurchaseActionPerformed

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        supplier.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        supplier.setVisible(true);
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnCapitalDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapitalDetActionPerformed
        entercapital();
    }//GEN-LAST:event_btnCapitalDetActionPerformed

    private void btnFinancialTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancialTransactionActionPerformed
        transaction.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        transaction.setVisible(true);
    }//GEN-LAST:event_btnFinancialTransactionActionPerformed

    private void btnAddCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCapitalActionPerformed
        capital.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        capital.setVisible(true);
    }//GEN-LAST:event_btnAddCapitalActionPerformed

    private void updateCapitalLabelOnOtherForm() {
        Capital capitalForm = new Capital();
        double currentCapital = capitalForm.getCurrentCapital();
        lblCurrentCapitalOnOtherForm.setText(String.format("%.2f $", currentCapital));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Pharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCapital;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnAddSupplierPurchase;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAlmostF;
    public javax.swing.JButton btnCapitalDet;
    private javax.swing.JButton btnCreateBill;
    private javax.swing.JButton btnCustomerDet;
    private javax.swing.JButton btnDrugsDet;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExpiredDrugs;
    private javax.swing.JButton btnFinancialTransaction;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPurchaseDet;
    private javax.swing.JButton btnPurchaseH;
    private javax.swing.JButton btnSearchDrug;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnSupplierDet;
    public javax.swing.JButton btnUserDet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblCurrentCapitalOnOtherForm;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lbl_LoginAs;
    private javax.swing.JLabel lbl_Type;
    public static javax.swing.JLabel time;
    public static javax.swing.JLabel today;
    // End of variables declaration//GEN-END:variables

    private void showDate() {
        d = new Date();
        dd = new SimpleDateFormat("dd-MM-yyyy");
        today.setText(dd.format(d));

        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat dd = new SimpleDateFormat("hh:mm:ss a");
                time.setText(dd.format(d));
            }
        }).start();
    }

    private void buttonvis() {

        btnAddUser.setVisible(false);
        btnAddDrug.setVisible(false);
        btnSearchDrug.setVisible(false);
        btnExpiredDrugs.setVisible(false);
        btnAlmostF.setVisible(false);
        btnAddCustomer.setVisible(false);
        btnCreateBill.setVisible(false);
        btnPurchaseH.setVisible(false);
        btnLogout.setVisible(false);
        btnAddSupplier.setVisible(false);
        btnAddSupplierPurchase.setVisible(false);
        btnAddCapital.setVisible(false);
        btnFinancialTransaction.setVisible(false);

    }

    private void entersupplier() {
        btnSupplierDet.setEnabled(false);
        btnCapitalDet.setEnabled(true);
        btnCustomerDet.setEnabled(true);
        btnPurchaseDet.setEnabled(true);
        btnUserDet.setEnabled(true);
        btnSettings.setEnabled(true);
        btnExit.setEnabled(true);
        btnAddSupplier.setVisible(true);
        btnAddSupplierPurchase.setVisible(true);
        btnAddCapital.setVisible(false);
        btnFinancialTransaction.setVisible(false);
        btnAddUser.setVisible(false);
        btnAddDrug.setVisible(false);
        btnSearchDrug.setVisible(false);
        btnExpiredDrugs.setVisible(false);
        btnAlmostF.setVisible(false);
        btnAddCustomer.setVisible(false);
        btnCreateBill.setVisible(false);
        btnPurchaseH.setVisible(false);
        btnLogout.setVisible(false);

    }

    private void entercapital() {
        btnCapitalDet.setEnabled(false);
        btnSupplierDet.setEnabled(true);
        btnCustomerDet.setEnabled(true);
        btnPurchaseDet.setEnabled(true);
        btnDrugsDet.setEnabled(true);
        btnUserDet.setEnabled(true);
        btnSettings.setEnabled(true);
        btnExit.setEnabled(true);
        btnAddCapital.setVisible(true);
        btnFinancialTransaction.setVisible(true);
        btnAddUser.setVisible(false);
        btnAddUser.setVisible(false);
        btnAddDrug.setVisible(false);
        btnSearchDrug.setVisible(false);
        btnExpiredDrugs.setVisible(false);
        btnAlmostF.setVisible(false);
        btnAddCustomer.setVisible(false);
        btnCreateBill.setVisible(false);
        btnPurchaseH.setVisible(false);
        btnLogout.setVisible(false);
    }

    private void enteruser() {
        btnUserDet.setEnabled(false);
        btnDrugsDet.setEnabled(true);
        btnPurchaseDet.setEnabled(true);
        btnCustomerDet.setEnabled(true);
        btnSupplierDet.setEnabled(true);
        btnCapitalDet.setEnabled(true);
        btnSettings.setEnabled(true);
        btnAddUser.setVisible(true);
        btnAddDrug.setVisible(false);
        btnSearchDrug.setVisible(false);
        btnCreateBill.setVisible(false);
        btnPurchaseH.setVisible(false);
        btnAddCustomer.setVisible(false);
        btnExpiredDrugs.setVisible(false);
        btnAlmostF.setVisible(false);
        btnLogout.setVisible(false);
        btnAddSupplier.setVisible(false);
        btnAddSupplierPurchase.setVisible(false);
        btnAddCapital.setVisible(false);
        btnFinancialTransaction.setVisible(false);

    }

    private void enterdrugs() {
        btnDrugsDet.setEnabled(false);
        btnUserDet.setEnabled(true);
        btnPurchaseDet.setEnabled(true);
        btnSettings.setEnabled(true);
        btnCapitalDet.setEnabled(true);
        btnSupplierDet.setEnabled(true);
        btnSearchDrug.setVisible(true);
        btnExpiredDrugs.setVisible(true);
        btnAddDrug.setVisible(true);
        btnAddUser.setVisible(false);
        btnAlmostF.setVisible(true);
        btnCreateBill.setVisible(false);
        btnPurchaseH.setVisible(false);
        btnAddCustomer.setVisible(false);
        btnLogout.setVisible(false);
        btnAddSupplier.setVisible(false);
        btnAddSupplierPurchase.setVisible(false);
        btnAddCapital.setVisible(false);
        btnFinancialTransaction.setVisible(false);

    }

    private void entercustomer() {
        btnCustomerDet.setEnabled(false);
        btnDrugsDet.setEnabled(true);
        btnUserDet.setEnabled(true);
        btnSettings.setEnabled(true);
        btnPurchaseDet.setEnabled(true);
        btnCapitalDet.setEnabled(true);
        btnAddCustomer.setVisible(true);
        btnCreateBill.setVisible(false);
        btnPurchaseH.setVisible(false);
        btnAddDrug.setVisible(false);
        btnSearchDrug.setVisible(false);
        btnExpiredDrugs.setVisible(false);
        btnAlmostF.setVisible(false);
        btnLogout.setVisible(false);
        btnAddSupplier.setVisible(false);
        btnAddSupplierPurchase.setVisible(false);
        btnSupplierDet.setEnabled(true);
        btnAddCapital.setVisible(false);
        btnFinancialTransaction.setVisible(false);
    }

    private void enterpurchase() {
        btnPurchaseDet.setEnabled(false);
        btnDrugsDet.setEnabled(true);
        btnUserDet.setEnabled(true);
        btnCustomerDet.setEnabled(true);
        btnSettings.setEnabled(true);
        btnAddCustomer.setVisible(false);
        btnCreateBill.setVisible(true);
        btnPurchaseH.setVisible(true);
        btnAddDrug.setVisible(false);
        btnSearchDrug.setVisible(false);
        btnExpiredDrugs.setVisible(false);
        btnAlmostF.setVisible(false);
        btnLogout.setVisible(false);
        btnAddSupplier.setVisible(false);
        btnAddSupplierPurchase.setVisible(false);
        btnSupplierDet.setEnabled(true);
        btnCapitalDet.setEnabled(true);
        btnAddCapital.setVisible(false);
        btnFinancialTransaction.setVisible(false);
    }

    private void settings() {
        btnSettings.setEnabled(false);
        btnUserDet.setEnabled(true);
        btnDrugsDet.setEnabled(true);
        btnPurchaseDet.setEnabled(true);
        btnCustomerDet.setEnabled(true);
        btnAddUser.setVisible(false);
        btnAddDrug.setVisible(false);
        btnSearchDrug.setVisible(false);
        btnCreateBill.setVisible(false);
        btnPurchaseH.setVisible(false);
        btnAddCustomer.setVisible(false);
        btnExpiredDrugs.setVisible(false);
        btnAlmostF.setVisible(false);
        btnLogout.setVisible(true);
        btnAddSupplier.setVisible(false);
        btnAddSupplierPurchase.setVisible(false);
        btnSupplierDet.setEnabled(true);
        btnCapitalDet.setEnabled(true);
        btnAddCapital.setVisible(false);
        btnFinancialTransaction.setVisible(false);
    }

}
